<?php

declare(strict_types=1);

namespace Starisian\Sparxstar\Photon;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * ACF local field group registrations.
 *
 * Registers the "User Details" field group on `acf/include_fields`.
 * This single consolidated group covers all contact, communication,
 * social, and card-visibility data for the Photon Business Card.
 *
 * Fields registered:
 *   spx_org_name          — Company / organisation name
 *   spx_role_title        — Professional title / job role
 *   spx_loc_addr_01       — Street address line 1
 *   spx_loc_addr_02       — Street address line 2
 *   spx_loc_city          — City
 *   spx_loc_region        — State / Province / Region
 *   spx_loc_postcode      — Postal / ZIP code
 *   spx_loc_country_code  — ISO 3166-1 alpha-3 country code (select)
 *   spx_rel_com_matrix    — Communication channels repeater (type + identifier)
 *   spx_rel_social_matrix — Social media accounts repeater (platform + URL)
 *   spx_img_brand_blob    — Logo / brand image
 *   spx_state_img_pub     — Share Profile Image toggle
 *   spx_state_card_active — Display Business Card toggle
 *
 * @package Starisian\Sparxstar\Photon
 * @since   0.5.0
 * @version 1.1.0
 */
final class AcfFields {

	/**
	 * Register the ACF action hook.
	 *
	 * Called once from {@see Bootloader::init()}.
	 *
	 * @return void
	 */
	public static function register(): void {
		add_action( 'acf/include_fields', [ self::class, 'register_fields' ] );
	}

	/**
	 * Register the "User Details" field group.
	 *
	 * Always active regardless of which other plugins are installed.
	 *
	 * @return void
	 */
	public static function register_fields(): void {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group(
			[
				'key'    => 'group_69d6a285c1a58',
				'title'  => 'User Details',
				'fields' => [
					[
						'key'       => 'field_spx_org_identifier',
						'label'     => 'Company',
						'name'      => 'spx_org_name',
						'type'      => 'text',
						'maxlength' => 200,
					],
					[
						'key'       => 'field_spx_role_descriptor',
						'label'     => 'Title',
						'name'      => 'spx_role_title',
						'type'      => 'text',
						'maxlength' => 200,
					],
					[
						'key'       => 'field_spx_loc_street_primary',
						'label'     => 'Address',
						'name'      => 'spx_loc_addr_01',
						'type'      => 'text',
						'maxlength' => 250,
					],
					[
						'key'       => 'field_spx_loc_street_secondary',
						'label'     => 'Address 2',
						'name'      => 'spx_loc_addr_02',
						'type'      => 'text',
						'maxlength' => 250,
					],
					[
						'key'               => 'field_spx_org_name',
						'label'             => 'Organisation Name (PWA)',
						'name'              => 'spx_org_name',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => 'Displayed as the installed app name on the device home screen. Leave blank to fall back to Company or Display Name.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [ 'width' => '', 'class' => '', 'id' => '' ],
						'default_value'     => '',
						'maxlength'         => 45,
						'allow_in_bindings' => 1,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					],
					[
						'key'               => 'field_spx_img_brand_blob',
						'label'             => 'Brand Icon (PWA)',
						'name'              => 'spx_img_brand_blob',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => 'Square PNG/SVG, minimum 512×512 px. Used as the app icon when the card is installed to a home screen.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [ 'width' => '', 'class' => '', 'id' => '' ],
						'return_format'     => 'array',
						'library'           => 'all',
						'min_width'         => 192,
						'min_height'        => 192,
						'max_width'         => '',
						'max_height'        => '',
						'allow_in_bindings' => 1,
					],
					[
						'key'               => 'field_69d6a4517ff0f',
						'label'             => 'Display Business Card',
						'name'              => 'spx_display_business_card',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [ 'width' => '', 'class' => '', 'id' => '' ],
						'message'           => 'Display the business card on the site.',
						'default_value'     => 1,
						'allow_in_bindings' => 1,
						'ui'                => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
						'key'       => 'field_spx_loc_municipality',
						'label'     => 'City',
						'name'      => 'spx_loc_city',
						'type'      => 'text',
						'maxlength' => 200,
					],
					[
						'key'       => 'field_spx_loc_subdivision',
						'label'     => 'State / Province / Region',
						'name'      => 'spx_loc_region',
						'type'      => 'text',
						'maxlength' => 200,
					],
					[
						'key'       => 'field_spx_loc_postal_index',
						'label'     => 'Postal Code',
						'name'      => 'spx_loc_postcode',
						'type'      => 'text',
						'maxlength' => 20,
					],
					[
						'key'           => 'field_spx_loc_nation_state',
						'label'         => 'Country',
						'name'          => 'spx_loc_country_code',
						'type'          => 'select',
						'choices'       => [
							'AFG' => 'AFG : افغانستان',
							'ALB' => 'ALB : Shqipëria',
							'DZA' => 'DZA : الجزائر',
							'AND' => 'AND : Andorra',
							'AGO' => 'AGO : Angola',
							'ATG' => 'ATG : Antigua and Barbuda',
							'ARG' => 'ARG : Argentina',
							'ARM' => 'ARM : Հայաստան',
							'AUS' => 'AUS : Australia',
							'AUT' => 'AUT : Österreich',
							'AZE' => 'AZE : Azərbaycan',
							'BHS' => 'BHS : Bahamas',
							'BHR' => 'BHR : البحرين',
							'BGD' => 'BGD : বাংলাদেশ',
							'BRB' => 'BRB : Barbados',
							'BLR' => 'BLR : Беларусь',
							'BEL' => 'BEL : België',
							'BLZ' => 'BLZ : Belize',
							'BEN' => 'BEN : Bénin',
							'BTN' => 'BTN : འབྲུག་ཡུལ་',
							'BOL' => 'BOL : Bolivia',
							'BIH' => 'BIH : Bosna i Hercegovina',
							'BWA' => 'BWA : Botswana',
							'BRA' => 'BRA : Brasil',
							'BRN' => 'BRN : Brunei',
							'BGR' => 'BGR : България',
							'BFA' => 'BFA : Burkina Faso',
							'BDI' => 'BDI : Burundi',
							'CPV' => 'CPV : Cabo Verde',
							'KHM' => 'KHM : កម្ពុជា',
							'CMR' => 'CMR : Cameroun',
							'CAN' => 'CAN : Canada',
							'CAF' => 'CAF : République centrafricaine',
							'TCD' => 'TCD : Tchad',
							'CHL' => 'CHL : Chile',
							'CHN' => 'CHN : 中国',
							'COL' => 'COL : Colombia',
							'COM' => 'COM : جزر القمر',
							'COG' => 'COG : Congo',
							'COD' => 'COD : République démocratique du Congo',
							'CRI' => 'CRI : Costa Rica',
							'CIV' => "CIV : Côte d'Ivoire",
							'HRV' => 'HRV : Hrvatska',
							'CUB' => 'CUB : Cuba',
							'CYP' => 'CYP : Κύπρος',
							'CZE' => 'CZE : Česko',
							'DNK' => 'DNK : Danmark',
							'DJI' => 'DJI : Djibouti',
							'DMA' => 'DMA : Dominica',
							'DOM' => 'DOM : República Dominicana',
							'ECU' => 'ECU : Ecuador',
							'EGY' => 'EGY : مصر',
							'SLV' => 'SLV : El Salvador',
							'GNQ' => 'GNQ : Guinea Ecuatorial',
							'ERI' => 'ERI : ኤርትራ',
							'EST' => 'EST : Eesti',
							'SWZ' => 'SWZ : eSwatini',
							'ETH' => 'ETH : ኢትዮጵያ',
							'FJI' => 'FJI : Fiji',
							'FIN' => 'FIN : Suomi',
							'FRA' => 'FRA : France',
							'GAB' => 'GAB : Gabon',
							'GMB' => 'GMB : Gambia',
							'GEO' => 'GEO : საქართველო',
							'DEU' => 'DEU : Deutschland',
							'GHA' => 'GHA : Ghana',
							'GRC' => 'GRC : Ελλάδα',
							'GRD' => 'GRD : Grenada',
							'GTM' => 'GTM : Guatemala',
							'GIN' => 'GIN : Guinée',
							'GNB' => 'GNB : Guiné-Bissau',
							'GUY' => 'GUY : Guyana',
							'HTI' => 'HTI : Haïti',
							'HND' => 'HND : Honduras',
							'HUN' => 'HUN : Magyarország',
							'ISL' => 'ISL : Ísland',
							'IND' => 'IND : भारत',
							'IDN' => 'IDN : Indonesia',
							'IRN' => 'IRN : ایران',
							'IRQ' => 'IRQ : العراق',
							'IRL' => 'IRL : Éire',
							'ISR' => 'ISR : יִשְׂרָאֵל',
							'ITA' => 'ITA : Italia',
							'JAM' => 'JAM : Jamaica',
							'JPN' => 'JPN : 日本',
							'JOR' => 'JOR : الأردن',
							'KAZ' => 'KAZ : Қазақстан',
							'KEN' => 'KEN : Kenya',
							'KIR' => 'KIR : Kiribati',
							'KWT' => 'KWT : الكويت',
							'KGZ' => 'KGZ : Кыргызстан',
							'LAO' => 'LAO : ລາວ',
							'LVA' => 'LVA : Latvija',
							'LBN' => 'LBN : لبنان',
							'LSO' => 'LSO : Lesotho',
							'LBR' => 'LBR : Liberia',
							'LBY' => 'LBY : ليبيا',
							'LIE' => 'LIE : Liechtenstein',
							'LTU' => 'LTU : Lietuva',
							'LUX' => 'LUX : Lëtzebuerg',
							'MDG' => 'MDG : Madagasikara',
							'MWI' => 'MWI : Malawi',
							'MYS' => 'MYS : Malaysia',
							'MDV' => 'MDV : ދިވެހިރާއްޖެ',
							'MLI' => 'MLI : Mali',
							'MLT' => 'MLT : Malta',
							'MHL' => 'MHL : Marshall Islands',
							'MRT' => 'MRT : موريتانيا',
							'MUS' => 'MUS : Maurice',
							'MEX' => 'MEX : México',
							'FSM' => 'FSM : Micronesia',
							'MDA' => 'MDA : Moldova',
							'MCO' => 'MCO : Monaco',
							'MNG' => 'MNG : Монгол улс',
							'MNE' => 'MNE : Crna Gora',
							'MAR' => 'MAR : المغرب',
							'MOZ' => 'MOZ : Moçambique',
							'MMR' => 'MMR : မြန်မာ',
							'NAM' => 'NAM : Namibia',
							'NRU' => 'NRU : Nauru',
							'NPL' => 'NPL : नेपाल',
							'NLD' => 'NLD : Nederland',
							'NZL' => 'NZL : New Zealand',
							'NIC' => 'NIC : Nicaragua',
							'NER' => 'NER : Niger',
							'NGA' => 'NGA : Nigeria',
							'PRK' => 'PRK : 조선',
							'MKD' => 'MKD : Северна Македонија',
							'NOR' => 'NOR : Norge',
							'OMN' => 'OMN : عمان',
							'PAK' => 'PAK : پاکستان',
							'PLW' => 'PLW : Palau',
							'PSE' => 'PSE : فلسطين',
							'PAN' => 'PAN : Panamá',
							'PNG' => 'PNG : Papua New Guinea',
							'PRY' => 'PRY : Paraguay',
							'PER' => 'PER : Perú',
							'PHL' => 'PHL : Pilipinas',
							'POL' => 'POL : Polska',
							'PRT' => 'PRT : Portugal',
							'QAT' => 'QAT : قطر',
							'ROU' => 'ROU : România',
							'RUS' => 'RUS : Россия',
							'RWA' => 'RWA : Rwanda',
							'KNA' => 'KNA : Saint Kitts and Nevis',
							'LCA' => 'LCA : Saint Lucia',
							'VCG' => 'VCG : Saint Vincent and the Grenadines',
							'WSM' => 'WSM : Samoa',
							'SMR' => 'SMR : San Marino',
							'STP' => 'STP : São Tomé e Príncipe',
							'SAU' => 'SAU : السعودية',
							'SEN' => 'SEN : Sénégal',
							'SRB' => 'SRB : Србија',
							'SYC' => 'SYC : Seychelles',
							'SLE' => 'SLE : Sierra Leone',
							'SGP' => 'SGP : Singapore',
							'SVK' => 'SVK : Slovensko',
							'SVN' => 'SVN : Slovenija',
							'SLB' => 'SLB : Solomon Islands',
							'SOM' => 'SOM : Soomaaliya',
							'ZAF' => 'ZAF : South Africa',
							'SSD' => 'SSD : South Sudan',
							'ESP' => 'ESP : España',
							'LKA' => 'LKA : ශ්‍රී ලංකාව',
							'SDN' => 'SDN : السودان',
							'SUR' => 'SUR : Suriname',
							'SWE' => 'SWE : Sverige',
							'CHE' => 'CHE : Schweiz',
							'SYR' => 'SYR : سوريا',
							'TWN' => 'TWN : 台灣',
							'TJK' => 'TJK : Тоҷикистон',
							'TZA' => 'TZA : Tanzania',
							'THA' => 'THA : ประเทศไทย',
							'TLS' => 'TLS : Timor-Leste',
							'TGO' => 'TGO : Togo',
							'TON' => 'TON : Tonga',
							'TTO' => 'TTO : Trinidad and Tobago',
							'TUN' => 'TUN : تونس',
							'TUR' => 'TUR : Türkiye',
							'TKM' => 'TKM : Türkmenistan',
							'TUV' => 'TUV : Tuvalu',
							'UGA' => 'UGA : Uganda',
							'UKR' => 'UKR : Україна',
							'ARE' => 'ARE : الإمارات العربية المتحدة',
							'GBR' => 'GBR : United Kingdom',
							'USA' => 'USA : United States',
							'URY' => 'URY : Uruguay',
							'UZB' => 'UZB : Oʻzbekiston',
							'VUT' => 'VUT : Vanuatu',
							'VAT' => 'VAT : Civitas Vaticana',
							'VEN' => 'VEN : Venezuela',
							'VNM' => 'VNM : Việt Nam',
							'YEM' => 'YEM : اليمن',
							'ZMB' => 'ZMB : Zambia',
							'ZWE' => 'ZWE : Zimbabwe',
						],
						'ui'            => 1,
						'ajax'          => 1,
						'return_format' => 'value',
					],
					[
						'key'          => 'field_spx_col_com_repeater',
						'label'        => 'Communication Channels',
						'name'         => 'spx_rel_com_matrix',
						'type'         => 'repeater',
						'instructions' => 'Add multiple telecommunication or messaging nodes.',
						'layout'       => 'table',
						'button_label' => 'Add Channel',
						'sub_fields'   => [
							[
								'key'           => 'field_spx_node_com_type',
								'label'         => 'Channel Type',
								'name'          => 'spx_node_key',
								'type'          => 'select',
								'choices'       => [
									'mobile'   => 'Mobile',
									'work'     => 'Work Phone',
									'home'     => 'Home Phone',
									'direct'   => 'Direct Line',
									'whatsapp' => 'WhatsApp',
									'telegram' => 'Telegram',
									'signal'   => 'Signal',
									'wechat'   => 'WeChat',
									'viber'    => 'Viber',
									'line'     => 'Line',
									'zalo'     => 'Zalo',
									'kakao'    => 'KakaoTalk',
									'fax'      => 'Fax',
									'teams'    => 'Microsoft Teams',
									'zoom'     => 'Zoom',
								],
								'return_format' => 'value',
							],
							[
								'key'          => 'field_spx_node_com_val',
								'label'        => 'Identifier / Number',
								'name'         => 'spx_node_val',
								'type'         => 'text',
								'maxlength'    => 25,
								'instructions' => 'Include country code prefix (e.g., +44).',
							],
						],
					],
					[
						'key'          => 'field_spx_col_social_external',
						'label'        => 'Social Media',
						'name'         => 'spx_rel_social_matrix',
						'type'         => 'repeater',
						'layout'       => 'table',
						'button_label' => 'Add Node',
						'sub_fields'   => [
							[
								'key'           => 'field_spx_node_platform_type',
								'label'         => 'Social Account',
								'name'          => 'spx_node_key',
								'type'          => 'select',
								'choices'       => [
									'amazon_music'  => 'Amazon Music',
									'apple_music'   => 'Apple Music',
									'audiomack'     => 'Audiomack',
									'baidu_tieba'   => 'Baidu Tieba',
									'bandcamp'      => 'Bandcamp',
									'behance'       => 'Behance',
									'bereal'        => 'BeReal',
									'bilibili'      => 'Bilibili',
									'bluesky'       => 'Bluesky',
									'caffeine'      => 'Caffeine',
									'deezer'        => 'Deezer',
									'discord'       => 'Discord',
									'douyin'        => 'Douyin',
									'dribbble'      => 'Dribbble',
									'facebook'      => 'Facebook',
									'flickr'        => 'Flickr',
									'github'        => 'GitHub',
									'instagram'     => 'Instagram',
									'kick'          => 'Kick',
									'kuaishou'      => 'Kuaishou',
									'lemmy'         => 'Lemmy',
									'line'          => 'Line',
									'linkedin'      => 'LinkedIn',
									'mastodon'      => 'Mastodon',
									'medium'        => 'Medium',
									'pandora'       => 'Pandora',
									'pinterest'     => 'Pinterest',
									'pixiv'         => 'Pixiv',
									'qq'            => 'QQ',
									'quora'         => 'Quora',
									'reddit'        => 'Reddit',
									'rumble'        => 'Rumble',
									'snapchat'      => 'Snapchat',
									'soundcloud'    => 'SoundCloud',
									'spotify'       => 'Spotify',
									'stack_overflow' => 'Stack Overflow',
									'telegram'      => 'Telegram',
									'threads'       => 'Threads',
									'tidal'         => 'Tidal',
									'tiktok'        => 'TikTok',
									'truth_social'  => 'Truth Social',
									'tumblr'        => 'Tumblr',
									'twitch'        => 'Twitch',
									'viber'         => 'Viber',
									'vk'            => 'VK',
									'vsco'          => 'VSCO',
									'whatsapp'      => 'WhatsApp',
									'wechat'        => 'WeChat',
									'weibo'         => 'Weibo',
									'xiaohongshu'   => 'Xiaohongshu',
									'x'             => 'X',
									'youtube'       => 'YouTube',
									'youtube_music' => 'YouTube Music',
									'zhihu'         => 'Zhihu',
								],
								'return_format' => 'value',
							],
							[
								'key'      => 'field_spx_node_uri_target',
								'label'    => 'Profile URL',
								'name'     => 'spx_node_val',
								'type'     => 'url',
								'required' => 1,
							],
						],
					],
					[
						'key'           => 'field_spx_media_blob_brand',
						'label'         => 'Logo / Image',
						'name'          => 'spx_img_brand_blob',
						'type'          => 'image',
						'return_format' => 'array',
						'preview_size'  => 'medium',
					],
					[
						'key'           => 'field_spx_bool_img_visibility',
						'label'         => 'Share Profile Image',
						'name'          => 'spx_state_img_pub',
						'type'          => 'true_false',
						'default_value' => 1,
						'ui'            => 1,
					],
					[
						'key'           => 'field_spx_bool_card_activation',
						'label'         => 'Display Business Card',
						'name'          => 'spx_state_card_active',
						'type'          => 'true_false',
						'default_value' => 1,
						'ui'            => 1,
					],
				],
				'location'     => [
					[
						[
							'param'    => 'user_form',
							'operator' => '==',
							'value'    => 'all',
						],
					],
				],
				'active'       => true,
				'show_in_rest' => 1,
			]
		);
	}
}
